# Generated by Django 5.1.2 on 2025-02-16 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchikru', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.propertytype', verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Актуально'), ('sold', 'Продано'), ('rented', 'Арендовано')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Описание категории недвижимости'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории недвижимости'),
        ),
        migrations.AlterField(
            model_name='favoriteadvertisement',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='favoriteadvertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=150, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='location',
            name='house',
            field=models.CharField(max_length=15, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=150, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='kluchikru.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='display_order',
            field=models.IntegerField(verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='description',
            field=models.TextField(verbose_name='Описание типа недвижимости'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название типа недвижимости'),
        ),
        migrations.AlterField(
            model_name='review',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchikru.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='advertisement_count',
            field=models.IntegerField(verbose_name='Объявления'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='user_count',
            field=models.IntegerField(verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('default', 'Пользователь')], default='default', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
